
DROP TABLE BOOK_SUBJECT;
DROP TABLE BOOK_AUTHOR;
DROP TABLE BOOK;
DROP TABLE STUDENT_OFFENCE;
DROP TABLE STUDENT;
DROP TABLE AUTHOR;
DROP TABLE SUBJECT;
DROP TABLE PROVINCE;
DROP TABLE HOSTEL;
DROP TABLE FACULTY;

CREATE TABLE IF NOT EXISTS `SELIT_Database`.`AUTHOR` (
  `Author_Number` INT NOT NULL AUTO_INCREMENT,
  `Author_Name` VARCHAR(40) NULL,
  PRIMARY KEY (`Author_Number`),
  UNIQUE INDEX `Author_Name_UNIQUE` (`Author_Name` ASC) VISIBLE);
  
CREATE TABLE IF NOT EXISTS `SELIT_Database`.`HOSTEL` (
  `Hostel_Number` INT NOT NULL AUTO_INCREMENT,
  `Hostel_Name` VARCHAR(20) NULL,
  PRIMARY KEY (`Hostel_Number`),
  UNIQUE INDEX `Hostel_Name_UNIQUE` (`Hostel_Name` ASC) VISIBLE);
  
CREATE TABLE IF NOT EXISTS `SELIT_Database`.`PROVINCE` (
  `Province_Number` INT NOT NULL AUTO_INCREMENT,
  `Province_Name` VARCHAR(20) NULL,
  PRIMARY KEY (`Province_Number`),
  UNIQUE INDEX `Province_Name_UNIQUE` (`Province_Name` ASC) VISIBLE);

CREATE TABLE IF NOT EXISTS `SELIT_Database`.`FACULTY` (
  `Faculty_Number` INT NOT NULL AUTO_INCREMENT,
  `Faculty_Name` VARCHAR(40) NULL,
  PRIMARY KEY (`Faculty_Number`),
  UNIQUE INDEX `Faculty_Name_UNIQUE` (`Faculty_Name` ASC) VISIBLE);

CREATE TABLE IF NOT EXISTS `SELIT_Database`.`SUBJECT` (
  `Subject_Number` INT NOT NULL AUTO_INCREMENT,
  `Subject_Code` VARCHAR(7) NULL,
  `Subject_Name` VARCHAR(200) NULL,
  `FACULTY_Faculty_Number` INT NOT NULL,
  PRIMARY KEY (`Subject_Number`),
  UNIQUE INDEX `Subject_Code_UNIQUE` (`Subject_Code` ASC) VISIBLE,
  INDEX `fk_SUBJECT_FACULTY1_idx` (`FACULTY_Faculty_Number` ASC) VISIBLE,
  CONSTRAINT `fk_SUBJECT_FACULTY1`
    FOREIGN KEY (`FACULTY_Faculty_Number`)
    REFERENCES `SELIT_Database`.`FACULTY` (`Faculty_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
  
CREATE TABLE IF NOT EXISTS `SELIT_Database`.`STUDENT` (
  `Student_Number` INT NOT NULL AUTO_INCREMENT,
  `First_Name` VARCHAR(50) NULL,
  `Last_Name` VARCHAR(40) NULL,
  `Contact_Number` VARCHAR(10) NULL,
  `Email_Address` VARCHAR(60) NULL,
  `Password` VARCHAR(60) NULL,
  `PROVINCE_Province_Number` INT NOT NULL,
  `HOSTEL_Hostel_Number` INT NOT NULL,
  `Student` INT,
  `Admin` INT,
  PRIMARY KEY (`Student_Number`),
  UNIQUE INDEX `Email_Address_UNIQUE` (`Email_Address` ASC) VISIBLE,
  INDEX `fk_STUDENT_PROVINCE_idx` (`PROVINCE_Province_Number` ASC) VISIBLE,
  INDEX `fk_STUDENT_HOSTEL1_idx` (`HOSTEL_Hostel_Number` ASC) VISIBLE,
  CONSTRAINT `fk_STUDENT_PROVINCE`
    FOREIGN KEY (`PROVINCE_Province_Number`)
    REFERENCES `SELIT_Database`.`PROVINCE` (`Province_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STUDENT_HOSTEL1`
    FOREIGN KEY (`HOSTEL_Hostel_Number`)
    REFERENCES `SELIT_Database`.`HOSTEL` (`Hostel_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS `SELIT_Database`.`STUDENT_OFFENCE` (
  `Offence_Number` INT NOT NULL AUTO_INCREMENT,
  `Reason` VARCHAR(50) NULL,
  `Type_Of_Offence` VARCHAR(10) NULL,
  `Date_Of_Offence` DATETIME NULL,
  `STUDENT_Student_Number` INT NOT NULL,
  PRIMARY KEY (`Offence_Number`),
  INDEX `fk_STUDENT_OFFENCE_STUDENT1_idx` (`STUDENT_Student_Number` ASC) VISIBLE,
  CONSTRAINT `fk_STUDENT_OFFENCE_STUDENT1`
    FOREIGN KEY (`STUDENT_Student_Number`)
    REFERENCES `SELIT_Database`.`STUDENT` (`Student_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS `SELIT_Database`.`BOOK` (
  `Book_Number` INT NOT NULL AUTO_INCREMENT,
  `Book_Name` VARCHAR(60) NOT NULL,
  `Book_Edition` VARCHAR(40) NULL,
  `Book_ISBN_10_Number` VARCHAR(10) NULL,
  `Book_ISBN_13_Number` VARCHAR(13) NULL,
  `Book_Price` DECIMAL(7,2) NULL,
  `Book_Type` VARCHAR(15) NULL,
  `Date_Placed` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `STUDENT_Student_Number` INT NOT NULL,
  PRIMARY KEY (`Book_Number`),
  INDEX `fk_BOOK_STUDENT1_idx` (`STUDENT_Student_Number` ASC) VISIBLE,
  CONSTRAINT `fk_BOOK_STUDENT1`
    FOREIGN KEY (`STUDENT_Student_Number`)
    REFERENCES `SELIT_Database`.`STUDENT` (`Student_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
CREATE TABLE IF NOT EXISTS `SELIT_Database`.`BOOK_AUTHOR` (
  `BOOK_Book_Number` INT NOT NULL,
  `AUTHOR_Author_Number` INT NOT NULL,
  PRIMARY KEY (`AUTHOR_Author_Number`, `BOOK_Book_Number`),
  INDEX `fk_AUTHOR_has_BOOK_BOOK1_idx` (`BOOK_Book_Number` ASC) VISIBLE,
  INDEX `fk_AUTHOR_has_BOOK_AUTHOR1_idx` (`AUTHOR_Author_Number` ASC) VISIBLE,
  CONSTRAINT `fk_AUTHOR_has_BOOK_AUTHOR1`
    FOREIGN KEY (`AUTHOR_Author_Number`)
    REFERENCES `SELIT_Database`.`AUTHOR` (`Author_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AUTHOR_has_BOOK_BOOK1`
    FOREIGN KEY (`BOOK_Book_Number`)
    REFERENCES `SELIT_Database`.`BOOK` (`Book_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
CREATE TABLE IF NOT EXISTS `SELIT_Database`.`BOOK_SUBJECT` (
  `BOOK_Book_Number` INT NOT NULL,
  `SUBJECT_Subject_Number` INT NOT NULL,
  PRIMARY KEY (`BOOK_Book_Number`, `SUBJECT_Subject_Number`),
  INDEX `fk_BOOK_has_SUBJECT_SUBJECT1_idx` (`SUBJECT_Subject_Number` ASC) VISIBLE,
  INDEX `fk_BOOK_has_SUBJECT_BOOK1_idx` (`BOOK_Book_Number` ASC) VISIBLE,
  CONSTRAINT `fk_BOOK_has_SUBJECT_BOOK1`
    FOREIGN KEY (`BOOK_Book_Number`)
    REFERENCES `SELIT_Database`.`BOOK` (`Book_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BOOK_has_SUBJECT_SUBJECT1`
    FOREIGN KEY (`SUBJECT_Subject_Number`)
    REFERENCES `SELIT_Database`.`SUBJECT` (`Subject_Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB




    